name: Run Get S3cr3tz

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        env:
          SECRET_ID: ${{secrets.ID}}
        run: |
          import os
          print(os.getenv("SECRET_ID"))
