name: Run Get Secret

on:
  workflow_call:
    secrets:
      access-token: 
        description: 'Token passado para o workflow'
        required: false

jobs:
  run_locust_test:
    name: Run Get
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      - 
        run: echo ${{secrets.ID}}
