name: Run Get Secret

on:
  workflow_call:
    secrets:
      access-token: 
        description: 'Token passado para o workflow'
        required: false

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        run: echo ${{secrets.ID}}
