name: Run Locust on CI

on:
  workflow_call:
    inputs:
      ID: ${{secrets.ID}}

jobs:
  run_locust_test:
    name: Run Locust Test ${{ inputs. ID }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      - 
        run: echo ${{inputs.ID}}
